module.exports = {
    'all ages': ['All ages', 'מיועד לכל הגילאים'],
    'for children age 7 and above': ['For children age 7 and above', 'לבני 7 ומעלה'],
    'children 7 or older': ['Children 7 or older', 'לבני 7 ומעלה'],
    'children': ['Children', 'ילדים'],
    '13 - teens 13 or older': ['Teens 13 or older', 'לבני 13 ומעלה'],
    'pg-13 - Teens 13 or older': ['Teens 13 or older', 'לבני 13 ומעלה'],
    'teens 13 or older': ['Teens 13 or older', 'לבני 13 ומעלה'],
    'teens': ['Teens', 'לבני 13 ומעלה'],
    'pg-13': ['Teens 13 or older', 'לבני 13 ומעלה'],
    '17+ (violence and profanity)': ['17+ (Violence and Profanity)', '17+ (אלימות ושפה גסה)'],
    '17+ (violence & profanity)': ['17+ (Violence and Profanity)', '17+ (אלימות ושפה גסה)'],
    'profanity': ['Profanity', 'שפה גסה'],
    'violence': ['Violence', 'אלימות'],
    'mild nudity': ['Mild Nudity', 'עירום חלקי'],
    'violence & profanity': ['Violence & Profanity', 'אלימות ושפה גסה'],
    'sexual language and imagery': ['Sexual Language and Imagery', 'גסויות ועירום'],
    'horror': ['Horror', 'אימה'],
    'ecchi': ['Ecchi', 'אצ׳י'],
    'kids': ['Kids', 'ילדים'],
    '': ['please report this', 'נא לדווח על זה']
};