module.exports = {
    "Action": ['Action', 'פעולה'],
    "Adventure": ['Adventure', 'הרפתקאה'],
    "Comedy": ['Comedy', 'קומדיה'],
    "Drama": ['Drama', 'דרמה'],
    "Sci-Fi": ['Sci-Fi', 'מד"ב'],
    "Space": ['Space', 'חלל'],
    "Mystery": ['Mystery', 'מיסתורין'],
    "Magic": ['Magic', 'קסם'],
    "Supernatural": ['Supernatural', 'על-טבעי'],
    "Police": ['Police', 'משטרה'],
    "Fantasy": ['Fantasy', 'פנטזיה'],
    "Sports": ['Sports', 'ספורט'],
    "Romance": ['Romance', 'רומנטיקה'],
    "Cars": ['Cars', 'מכוניות'],
    "Slice of Life": ['Slice of Life', 'חלק-מן-החיים'],
    "Racing": ['Racing', 'מרוץ'],
    "Horror": ['Horror', 'אימה'],
    "Psychological": ['Psychological', 'פסיכולוגי'],
    "Thriller": ['Thriller', 'מתח'],
    "Martial Arts": ['Martial Arts', 'אומנות-לחימה'],
    "Super Power": ['Super Power', 'כוחות-על'],
    "School": ['School', 'בית-ספר'],
    "Ecchi": ['Ecchi', "אצ'י"],
    "Vampire": ['Vampire', 'ערפדים'],
    "Historical": ['Historical', 'הסטורי'],
    "Military": ['Military', 'צבא'],
    "Dementia": ['Dementia', 'דמנציה'],
    "Mecha": ['Mecha', 'מכה'],
    "Demons": ['Demons', 'שדים'],
    "Samurai": ['Samurai', 'סמוראי'],
    "Harem": ['Harem', 'הארם'],
    "Music": ['Music', 'מוזיקה'],
    "Parody": ['Parody', 'פארודיה'],
    "Shoujo Ai": ['Shoujo Ai', "שוג'ו-איי"],
    "Game": ['Game', 'משחק'],
    "Shounen Ai": ['Shounen Ai', "שונן-איי"],
    "Kids": ['Kids', 'ילדים'],
    "Hentai": ['Hentai', 'הנטאי'],
    "Yuri": ['Yuri', 'יורי'],
    "Yaoi": ['Yaoi', 'יאוי'],
    "Anime Influenced": ['Anime Influenced', 'מושפע מאנימה'],
    "Gender Bender": ['Gender Bender', "ג'נדר-בנדר"],
    "Doujinshi": ['Doujinshi', "דוג'ינשי"],
    "Mahou Shoujo": ['Mahou Shoujo', "מאהו-שוג'ו"],
    "Mahou Shounen": ['Mahou Shounen', 'מאהו-שונן'],
    "Gore": ['Gore', 'הרג'],
    "Law": ['Law', 'חוק'],
    "Cooking": ['Cooking', 'בישול'],
    "Mature": ['Mature', 'סיינן'],
    "Medical": ['Medical', 'רפואה'],
    "Political": ['Political', 'פוליטיקה'],
    "Tokusatsu": ['Tokusatsu', 'טוקוסטסו'],
    "Youth": ['Youth', 'נעורים'],
    "Workplace": ['Workplace', 'מקום-עבודה'],
    "Crime": ['Crime', 'פשע'],
    "Zombies": ['Zombies', 'זומבים'],
    "Documentary": ['Documentary', 'דוקומנטרי'],
    "Family": ['Family', 'משפחה'],
    "Food": ['Food', 'אוכל'],
    "Friendship": ['Friendship', 'חברות'],
    "Tragedy": ['Tragedy', 'טרגדיה']
}